Repository ocp-power-automation/openshift-install-power, pull requests merged in 2021-06, with the labels that each got.

#164 Support usage of IBM Cloud services
  docs/variables.md
  openshift-install-powervs
Labels: enhancement, lgtm, size/M

#167 # OpenShift UPI Install Helper for Power Virtual Servers 1.2.1
  VERSION
  docs/variables.md
  openshift-install-powervs
Labels: size/M

#169 Remove cygwin workflow
  .github/workflows/cygwin.yml
Labels: lgtm, size/M

#170 Change error return code to 1
  openshift-install-powervs
Labels: size/XS

#171 Update version to 1.2.2
  VERSION
Labels: size/XS

#172 Forward port from devel to master
  .github/workflows/cygwin.yml
  VERSION
  openshift-install-powervs
Labels: size/M

#174 Document update on how to use the docker image
  .travis.yml
  README.md
  docs/container.md
Labels: lgtm, size/L
