Repository ocp-power-automation/openshift-install-power, pull requests merged in 2022-01, with the labels that each got.

#187 Updated expression as per curl output
  openshift-install-powervs
Labels: lgtm, size/XS, approved

#188 Add curl insecure option for downloading oc
  openshift-install-powervs
Labels: size/S, lgtm, approved

#189 Check for script version to update
  openshift-install-powervs
Labels: size/M, lgtm, approved

#191 Filtering the required versions from the curl output
  openshift-install-powervs
Labels: size/S, lgtm, approved
